### ISSUE TITLE
stages

### ISSUE THREAD

**Issue by bkardell** [jonathantneal/css-db#1]
Both stage 1 and stage 2 should probably include something about "and possible failure".  Just because we take up experiments or agree that "this idea isn't entirely crazy" doesn't mean that we will not either:
  *  come up with something better that covers many of the same use cases. 
  * decide that, actually, upon deeper investigation, it is kind of crazy.

I think it needs to be clear that using an approximation of an early idea serves two purposes: 
  * it allows developers to accomplish real things.  
 * it allows developers to understand/be more easily involved with standards creation/testing/feedback/understanding new use cases in the _experiment_.

**Comment by jonathantneal** [comment]
This is true, and I can adjust the deeper language on this. Let me see if/how I can use what you’ve put here.

**Comment by jonathantneal** [comment]
Thanks for this. I’m resolving this via https://github.com/jonathantneal/css-db/commit/78764fa0463fa943a0cc5d211edaf6c344e7222c and https://github.com/jonathantneal/css-db/commit/942975c300df7e9fdad7c646f50411d9f99e00d6

**Comment by SelenIT** [comment]
Maybe it's not worth opening a new issue, but I'd like to clarify: aren't there any extra criteria of matching the stages for the features besides the latest published version of the spec maturity status? For example, currently Custom Properties are marked as Stage 5 and Grid Layout is marked as Stage 4, while both specs are currently Candidate Recommendations...

**Comment by SelenIT** [comment]
@jonathantneal, could you please answer my question from the above comment (why Custom Properties are Stage 5 and Grid is Stage 4, while both specs are CRs and browser support is nearly the same)?

**Comment by jonathantneal** [comment]
@SelenIT, yes, that looks like a bug! Filed https://github.com/jonathantneal/css-db/issues/14
